spring:
  #mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thehouse?autoReconnect=true&serverTimezone=UTC
    username: root
    password: 1234
  #jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: th/*
  devtools:
    livereload:
      enabled: true

# server port
server:
  port: 8080

# mybatis 설정.
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.bit.house.domain
